# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName(_fromUtf8("Options"))
        Options.resize(668, 480)
        self.gridLayout = QtGui.QGridLayout(Options)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(Options)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.widget_4 = QtGui.QWidget(self.widget_2)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.topcheck = QtGui.QCheckBox(self.widget_4)
        self.topcheck.setText(_fromUtf8(""))
        self.topcheck.setObjectName(_fromUtf8("topcheck"))
        self.gridLayout_4.addWidget(self.topcheck, 1, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.label_2 = QtGui.QLabel(self.widget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.xtickcombo = QtGui.QComboBox(self.widget_4)
        self.xtickcombo.setObjectName(_fromUtf8("xtickcombo"))
        self.xtickcombo.addItem(_fromUtf8(""))
        self.xtickcombo.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.xtickcombo, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.leftcheck = QtGui.QCheckBox(self.widget_4)
        self.leftcheck.setText(_fromUtf8(""))
        self.leftcheck.setObjectName(_fromUtf8("leftcheck"))
        self.gridLayout_4.addWidget(self.leftcheck, 2, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.ytickcombo = QtGui.QComboBox(self.widget_4)
        self.ytickcombo.setObjectName(_fromUtf8("ytickcombo"))
        self.ytickcombo.addItem(_fromUtf8(""))
        self.ytickcombo.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.ytickcombo, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_5 = QtGui.QLabel(self.widget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_3.addWidget(self.widget_4, 3, 0, 1, 3)
        self.line = QtGui.QFrame(self.widget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 3)
        self.label = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.widget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.legendsize = QtGui.QComboBox(self.widget_3)
        self.legendsize.setObjectName(_fromUtf8("legendsize"))
        self.legendsize.addItem(_fromUtf8(""))
        self.legendsize.addItem(_fromUtf8(""))
        self.legendsize.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.legendsize, 4, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 3, 0, 1, 1)
        self.linewidth = QtGui.QDoubleSpinBox(self.widget_3)
        self.linewidth.setObjectName(_fromUtf8("linewidth"))
        self.gridLayout_5.addWidget(self.linewidth, 3, 1, 1, 1)
        self.fontsize = QtGui.QDoubleSpinBox(self.widget_3)
        self.fontsize.setObjectName(_fromUtf8("fontsize"))
        self.gridLayout_5.addWidget(self.fontsize, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 3, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.widget_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_5.addWidget(self.line_2, 1, 0, 1, 4)
        self.label_10 = QtGui.QLabel(self.widget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 4, 2, 1, 1)
        self.markersize = QtGui.QDoubleSpinBox(self.widget_3)
        self.markersize.setObjectName(_fromUtf8("markersize"))
        self.gridLayout_5.addWidget(self.markersize, 3, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.widget_6 = QtGui.QWidget(self.widget_3)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.newlegend = QtGui.QCheckBox(self.widget_6)
        self.newlegend.setObjectName(_fromUtf8("newlegend"))
        self.gridLayout_7.addWidget(self.newlegend, 0, 1, 1, 1)
        self.scaledash = QtGui.QCheckBox(self.widget_6)
        self.scaledash.setObjectName(_fromUtf8("scaledash"))
        self.gridLayout_7.addWidget(self.scaledash, 0, 0, 1, 1)
        self.newcycle = QtGui.QCheckBox(self.widget_6)
        self.newcycle.setObjectName(_fromUtf8("newcycle"))
        self.gridLayout_7.addWidget(self.newcycle, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.widget_6, 2, 0, 1, 5)
        self.gridLayout_2.addWidget(self.widget_3, 2, 0, 1, 1)
        self.widget_5 = QtGui.QWidget(self.widget)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_11 = QtGui.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.tickmat2 = QtGui.QRadioButton(self.widget_5)
        self.tickmat2.setObjectName(_fromUtf8("tickmat2"))
        self.gridLayout_6.addWidget(self.tickmat2, 2, 1, 1, 1)
        self.tickmat1 = QtGui.QRadioButton(self.widget_5)
        self.tickmat1.setObjectName(_fromUtf8("tickmat1"))
        self.gridLayout_6.addWidget(self.tickmat1, 2, 0, 1, 1)
        self.tickcust = QtGui.QRadioButton(self.widget_5)
        self.tickcust.setObjectName(_fromUtf8("tickcust"))
        self.gridLayout_6.addWidget(self.tickcust, 2, 2, 1, 1)
        self.line_3 = QtGui.QFrame(self.widget_5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 1, 0, 1, 3)
        self.gridLayout_2.addWidget(self.widget_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Options)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        Options.setWindowTitle(_translate("Options", "Preferences", None))
        self.label_4.setText(_translate("Options", "Top ticks", None))
        self.label_2.setText(_translate("Options", "Xtick Direction", None))
        self.xtickcombo.setItemText(0, _translate("Options", "in", None))
        self.xtickcombo.setItemText(1, _translate("Options", "out", None))
        self.label_3.setText(_translate("Options", "Ytick DIrection", None))
        self.ytickcombo.setItemText(0, _translate("Options", "in", None))
        self.ytickcombo.setItemText(1, _translate("Options", "out", None))
        self.label_5.setText(_translate("Options", "Left ticks", None))
        self.label.setText(_translate("Options", "Ticks", None))
        self.label_9.setText(_translate("Options", "Font Size", None))
        self.legendsize.setItemText(0, _translate("Options", "large", None))
        self.legendsize.setItemText(1, _translate("Options", "medium", None))
        self.legendsize.setItemText(2, _translate("Options", "small", None))
        self.label_7.setText(_translate("Options", "Line Width", None))
        self.label_8.setText(_translate("Options", "Marker Size", None))
        self.label_10.setText(_translate("Options", "Legend Font Size", None))
        self.label_6.setText(_translate("Options", "Plotting Style", None))
        self.newlegend.setText(_translate("Options", "New Style Legend", None))
        self.scaledash.setText(_translate("Options", "Scale dashes", None))
        self.newcycle.setText(_translate("Options", "New Color Cycle", None))
        self.label_11.setText(_translate("Options", "General Options", None))
        self.tickmat2.setText(_translate("Options", "Matplotlib2", None))
        self.tickmat1.setText(_translate("Options", "Matplotlib 1", None))
        self.tickcust.setText(_translate("Options", "Custom", None))

